name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

permissions:
  contents: write

jobs:
  release:
    uses: DND-IT/github-workflows/.github/workflows/gh-release-on-main.yaml@v3
    with:
      update_version_aliases: false
